#!/bin/bash

# Get username of the currently logged in user
username=$(who | cut -d' ' -f1 | sort | uniq)

case "$2" in
        up)
			systemctl restart insync@"${username}"
        ;;
        down)
			[[ "$(nmcli n connectivity check)" == "full" ]] || systemctl stop insync@"${username}"
        ;;
esac
